// ============================================================
//  塗り絵・脳トレ・カレンダーの登録リスト
//  ※ このファイルは管理ページ(admin.html)から自動で更新されます。
// ============================================================

window.NURIE_LIST = [
  { season: "夏", genre: "花", title: "あじさい", diff: "中級", file: "ajisai_chu.png" },
  { season: "夏", genre: "花", title: "ひまわり", diff: "初級", file: "himawari_sho.png" },
  { season: "夏", genre: "花", title: "ひまわり", diff: "中級", file: "himawari_chu.png" },
  { season: "夏", genre: "花", title: "ひまわり", diff: "上級", file: "himawari_jo.png" },
  { season: "夏", genre: "花", title: "ひまわり畑", diff: "上級", file: "himawari_batake_jo.png" },
  { season: "夏", genre: "花", title: "ほおずき", diff: "中級", file: "hozuki_chu.png" },
  { season: "夏", genre: "花", title: "ゆり", diff: "中級", file: "yuri_chu.png" },
  { season: "夏", genre: "花", title: "アサガオ", diff: "中級", file: "asagao_chu.png" },
  { season: "夏", genre: "花", title: "オシロイバナ", diff: "中級", file: "oshiroibana_chu.png" },
  { season: "夏", genre: "花", title: "クチナシ", diff: "中級", file: "kuchinashi_chu.png" },
  { season: "夏", genre: "花", title: "スイレン", diff: "中級", file: "suiren_chu.png" },
  { season: "夏", genre: "花", title: "ダリア", diff: "中級", file: "dahlia_chu.png" },
  { season: "夏", genre: "花", title: "ノウゼンカズラ", diff: "中級", file: "nouzenkazura_chu.png" },
  { season: "夏", genre: "花", title: "ハイビスカス", diff: "中級", file: "hibiscus_chu.png" },
  { season: "夏", genre: "花", title: "ハナショウブ", diff: "中級", file: "hanashobu_chu.png" },
  { season: "夏", genre: "花", title: "マリーゴールド", diff: "中級", file: "marigold_chu.png" },
  { season: "夏", genre: "花", title: "ラベンダー", diff: "中級", file: "lavender_chu.png" },
  { season: "夏", genre: "花", title: "百日紅", diff: "中級", file: "sarusuberi_chu.png" },
  { season: "夏", genre: "花", title: "蓮", diff: "中級", file: "hasu_chu.png" },
  { season: "夏", genre: "食べ物", title: "かき氷", diff: "初級", file: "kakigori_sho.png" },
  { season: "夏", genre: "食べ物", title: "すいか", diff: "初級", file: "suika_sho.png" },
  { season: "夏", genre: "食べ物", title: "夏の果物", diff: "初級", file: "natsu_kudamono_sho.png" },
  { season: "夏", genre: "食べ物", title: "夏野菜", diff: "初級", file: "natsu_yasai_sho.png" },
  { season: "夏", genre: "食べ物", title: "夏野菜", diff: "中級", file: "natsu_yasai_chu.png" },
  { season: "夏", genre: "食べ物", title: "夏野菜", diff: "上級", file: "natsu_yasai_jo.png" },
  { season: "夏", genre: "食べ物", title: "とうもろこし", diff: "初級", file: "toumorokoshi_sho.png" },
  { season: "夏", genre: "風物詩", title: "うちわ", diff: "初級", file: "uchiwa_sho.png" },
  { season: "夏", genre: "風物詩", title: "うちわと金魚鉢", diff: "初級", file: "uchiwa_kingyo_sho.png" },
  { season: "夏", genre: "風物詩", title: "すだれ風鈴", diff: "中級", file: "sudare_furin_chu.png" },
  { season: "夏", genre: "風物詩", title: "すだれ風鈴", diff: "上級", file: "sudare_furin_jo.png" },
  { season: "夏", genre: "行事", title: "よーよーつり", diff: "初級", file: "yoyo_tsuri_sho.png" },
  { season: "夏", genre: "行事", title: "よーよーつり", diff: "中級", file: "yoyo_tsuri_chu.png" },
  { season: "夏", genre: "行事", title: "夏まつり", diff: "上級", file: "natsu_matsuri_jo.png" },
  { season: "夏", genre: "行事", title: "夏祭り", diff: "初級", file: "natsu_matsuri_sho.png" },
  { season: "夏", genre: "行事", title: "夏祭り", diff: "中級", file: "natsu_matsuri_chu.png" },
  { season: "夏", genre: "行事", title: "祇園祭", diff: "上級", file: "gion_matsuri_jo.png" },
  { season: "夏", genre: "行事", title: "精霊馬", diff: "初級", file: "shoryo_uma_sho.png" },
  { season: "夏", genre: "行事", title: "精霊馬", diff: "上級", file: "shoryo_uma_jo.png" },
  { season: "夏", genre: "行事", title: "花火", diff: "中級", file: "hanabi_chu.png" },
  { season: "夏", genre: "行事", title: "花火", diff: "上級", file: "hanabi_jo.png" },
  { season: "夏", genre: "行事", title: "金魚すくい", diff: "中級", file: "kingyo_sukui_chu.png" },
  { season: "夏", genre: "風景", title: "夏", diff: "初級", file: "natsu_sho.png" },
  { season: "夏", genre: "風景", title: "夏", diff: "中級", file: "natsu_chu.png" },
  { season: "夏", genre: "風景", title: "夏", diff: "上級", file: "natsu_jo.png" },
  { season: "夏", genre: "風景", title: "夏の海", diff: "中級", file: "natsu_umi_chu.png" },
  { season: "夏", genre: "風景", title: "夏の海", diff: "上級", file: "natsu_umi_jo.png" },
  { season: "夏", genre: "動物", title: "蝉取り", diff: "中級", file: "semitori_chu.png" },
  { season: "通年", genre: "動物", title: "うさぎ", diff: "初級", file: "usagi_sho.png" },
  { season: "通年", genre: "動物", title: "うさぎ", diff: "中級", file: "usagi_chu.png" },
  { season: "通年", genre: "動物", title: "くじら", diff: "中級", file: "kujira_chu.png" },
  { season: "通年", genre: "動物", title: "しば犬", diff: "中級", file: "shibainu_chu.png" },
  { season: "通年", genre: "動物", title: "しば犬と猫", diff: "上級", file: "shibainu_neko_jo.png" },
  { season: "通年", genre: "動物", title: "ふくろう", diff: "中級", file: "fukurou_chu.png" },
  { season: "通年", genre: "動物", title: "アヒル", diff: "初級", file: "ahiru_sho.png" },
  { season: "通年", genre: "動物", title: "インコ", diff: "中級", file: "inko_chu.png" },
  { season: "通年", genre: "動物", title: "サバンナ", diff: "上級", file: "savanna_jo.png" },
  { season: "通年", genre: "動物", title: "ハムスター", diff: "初級", file: "hamster_sho.png" },
  { season: "通年", genre: "動物", title: "動物園", diff: "初級", file: "doubutsuen_sho.png" },
  { season: "通年", genre: "動物", title: "動物園", diff: "上級", file: "doubutsuen_jo.png" },
  { season: "通年", genre: "動物", title: "海の生き物", diff: "初級", file: "umi_ikimono_sho.png" },
  { season: "通年", genre: "動物", title: "海の生き物 その2", diff: "初級", file: "umi_ikimono_sho_2.png" },
  { season: "通年", genre: "動物", title: "熊", diff: "初級", file: "kuma_sho.png" },
  { season: "通年", genre: "動物", title: "犬", diff: "初級", file: "inu_sho.png" },
  { season: "通年", genre: "動物", title: "犬", diff: "中級", file: "inu_chu.png" },
  { season: "通年", genre: "動物", title: "犬と猫", diff: "初級", file: "inu_neko_sho.png" },
  { season: "通年", genre: "動物", title: "犬と猫", diff: "中級", file: "inu_neko_chu.png" },
  { season: "通年", genre: "動物", title: "犬と猫", diff: "上級", file: "inu_neko_jo.png" },
  { season: "通年", genre: "動物", title: "犬種", diff: "初級", file: "inushu_sho.png" },
  { season: "通年", genre: "動物", title: "狼", diff: "初級", file: "ookami_sho.png" },
  { season: "通年", genre: "動物", title: "狼", diff: "上級", file: "ookami_jo.png" },
  { season: "通年", genre: "動物", title: "猫", diff: "初級", file: "neko_sho.png" },
  { season: "通年", genre: "動物", title: "猫", diff: "中級", file: "neko_chu.png" },
  { season: "通年", genre: "動物", title: "猫", diff: "上級", file: "neko_jo.png" },
  { season: "通年", genre: "動物", title: "猫カフェ", diff: "上級", file: "neko_cafe_jo.png" },
  { season: "通年", genre: "動物", title: "羊", diff: "中級", file: "hitsuji_chu.png" },
  { season: "通年", genre: "動物", title: "羊", diff: "上級", file: "hitsuji_jo.png" },
  { season: "通年", genre: "動物", title: "蝶を追いかける猫", diff: "中級", file: "chou_neko_chu.png" },
  { season: "通年", genre: "動物", title: "金魚", diff: "上級", file: "kingyo_jo.png" },
  { season: "通年", genre: "動物", title: "馬", diff: "中級", file: "uma_chu.png" },
  { season: "通年", genre: "動物", title: "馬", diff: "上級", file: "uma_jo.png" },
  { season: "通年", genre: "動物", title: "庭の猫", diff: "上級", file: "niwa_neko.png" },
  { season: "通年", genre: "風景", title: "田園風景", diff: "上級", file: "denen_fukei.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字(魚へん)", diff: "中級", file: "nandoku_kanji_sakana.png", answer: "nandoku_kanji_sakana_kotae.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "3文字しりとり", diff: "初級", file: "shiritori_3moji.png", answer: "shiritori_3moji_kotae.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ絵クイズ その1", diff: "中級", file: "kotowaza_quiz_1.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ絵クイズ その2", diff: "中級", file: "kotowaza_quiz_2.png" },
  { kind: "カレンダー", year: 2026, month: 8, season: "通年", title: "8月カレンダー", file: "calendar_2026_08.png" },
  { kind: "カレンダー", year: 2026, month: 8, season: "通年", title: "8月カレンダー(貼り付け用)", file: "calendar_2026_08_blank.png" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー", file: "calendar_2026_09.png" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー(貼り付け用)", file: "calendar_2026_09_blank.png" },
  { kind: "カレンダー", year: 2026, month: 10, season: "通年", title: "10月カレンダー(貼り付け用)", file: "calendar_2026_10_blank.png" },
  // ---- 秋の塗り絵 60枚 ----
  { season: "秋", genre: "花", title: "きんもくせい", diff: "中級", file: "kinmokusei_chu.png" },
  { season: "秋", genre: "花", title: "コスモス", diff: "初級", file: "cosmos_sho.png" },
  { season: "秋", genre: "花", title: "コスモス", diff: "中級", file: "cosmos_chu.png" },
  { season: "秋", genre: "花", title: "コスモス", diff: "上級", file: "cosmos_jo.png" },
  { season: "秋", genre: "花", title: "コスモス2", diff: "初級", file: "cosmos2_sho.png" },
  { season: "秋", genre: "花", title: "コスモス2", diff: "中級", file: "cosmos2_chu.png" },
  { season: "秋", genre: "花", title: "コスモス3", diff: "中級", file: "cosmos3_chu.png" },
  { season: "秋", genre: "花", title: "サフラン", diff: "中級", file: "saffron_chu.png" },
  { season: "秋", genre: "花", title: "ダリア", diff: "中級", file: "dahlia_aki_chu.png" },
  { season: "秋", genre: "花", title: "バラ", diff: "中級", file: "bara_aki_chu.png" },
  { season: "秋", genre: "花", title: "ホトトギス", diff: "中級", file: "hototogisu_chu.png" },
  { season: "秋", genre: "花", title: "リンドウ", diff: "中級", file: "rindou_chu.png" },
  { season: "秋", genre: "花", title: "孔雀草", diff: "中級", file: "kujakusou_chu.png" },
  { season: "秋", genre: "花", title: "桔梗", diff: "中級", file: "kikyou_chu.png" },
  { season: "秋", genre: "花", title: "秋の七草", diff: "中級", file: "aki_nanakusa_chu.png" },
  { season: "秋", genre: "花", title: "菊", diff: "中級", file: "kiku_aki_chu.png" },
  { season: "秋", genre: "食べ物", title: "おでん", diff: "初級", file: "oden_sho.png" },
  { season: "秋", genre: "食べ物", title: "おはぎ", diff: "中級", file: "ohagi_chu.png" },
  { season: "秋", genre: "食べ物", title: "さんまの塩焼き", diff: "初級", file: "sanma_shioyaki_sho.png" },
  { season: "秋", genre: "食べ物", title: "ぶどうと梨", diff: "中級", file: "budou_nashi_chu.png" },
  { season: "秋", genre: "食べ物", title: "みかんとりんご", diff: "初級", file: "mikan_ringo_sho.png" },
  { season: "秋", genre: "食べ物", title: "千歳飴", diff: "初級", file: "chitoseame_sho.png" },
  { season: "秋", genre: "食べ物", title: "干し柿", diff: "初級", file: "hoshigaki_sho.png" },
  { season: "秋", genre: "食べ物", title: "柿", diff: "初級", file: "kaki_sho.png" },
  { season: "秋", genre: "食べ物", title: "栗ご飯", diff: "初級", file: "kurigohan_sho.png" },
  { season: "秋", genre: "食べ物", title: "焼き芋", diff: "中級", file: "yakiimo_chu.png" },
  { season: "秋", genre: "食べ物", title: "秋のキノコ", diff: "初級", file: "aki_kinoko_sho.png" },
  { season: "秋", genre: "食べ物", title: "秋の味覚", diff: "上級", file: "aki_mikaku_jo.png" },
  { season: "秋", genre: "食べ物", title: "銀杏", diff: "初級", file: "ginnan_sho.png" },
  { season: "秋", genre: "行事", title: "お彼岸", diff: "上級", file: "ohigan_jo.png" },
  { season: "秋", genre: "行事", title: "お月見", diff: "中級", file: "otsukimi_chu.png" },
  { season: "秋", genre: "行事", title: "だんじり祭り", diff: "上級", file: "danjiri_jo.png" },
  { season: "秋", genre: "行事", title: "ハロウィン", diff: "中級", file: "halloween_chu.png" },
  { season: "秋", genre: "行事", title: "ハロウィン", diff: "上級", file: "halloween_jo.png" },
  { season: "秋", genre: "行事", title: "七五三", diff: "上級", file: "shichigosan_jo.png" },
  { season: "秋", genre: "行事", title: "中秋の名月", diff: "上級", file: "chushu_meigetsu_jo.png" },
  { season: "秋", genre: "行事", title: "敬老の日", diff: "中級", file: "keirou_chu.png" },
  { season: "秋", genre: "行事", title: "敬老の日", diff: "上級", file: "keirou_jo.png" },
  { season: "秋", genre: "行事", title: "文化の日", diff: "中級", file: "bunka_no_hi_chu.png" },
  { season: "秋", genre: "行事", title: "月見", diff: "初級", file: "tsukimi1_sho.png" },
  { season: "秋", genre: "行事", title: "月見2", diff: "初級", file: "tsukimi2_sho.png" },
  { season: "秋", genre: "行事", title: "月見のうさぎ", diff: "中級", file: "tsukimi_usagi_chu.png" },
  { season: "秋", genre: "行事", title: "紅葉狩り", diff: "初級", file: "momijigari_sho.png" },
  { season: "秋", genre: "行事", title: "紅葉狩り", diff: "上級", file: "momijigari_jo.png" },
  { season: "秋", genre: "行事", title: "芋ほり", diff: "上級", file: "imohori_jo.png" },
  { season: "秋", genre: "行事", title: "運動会", diff: "上級", file: "undoukai_aki_jo.png" },
  { season: "秋", genre: "風物詩", title: "いちょう", diff: "上級", file: "icho_jo.png" },
  { season: "秋", genre: "風物詩", title: "すずむし", diff: "中級", file: "suzumushi_chu.png" },
  { season: "秋", genre: "風物詩", title: "どんぐりとまつぼっくり", diff: "初級", file: "donguri_matsubokkuri_sho.png" },
  { season: "秋", genre: "風物詩", title: "焼き芋屋", diff: "中級", file: "yakiimoya_chu.png" },
  { season: "秋", genre: "風物詩", title: "白露", diff: "中級", file: "hakuro_chu.png" },
  { season: "秋", genre: "風物詩", title: "白露2", diff: "中級", file: "hakuro2_chu.png" },
  { season: "秋", genre: "風物詩", title: "稲刈り", diff: "上級", file: "inekari_jo.png" },
  { season: "秋", genre: "風物詩", title: "稲刈り2", diff: "上級", file: "inekari2_jo.png" },
  { season: "秋", genre: "風物詩", title: "紅葉", diff: "中級", file: "kouyou_chu.png" },
  { season: "秋", genre: "風物詩", title: "落ち葉焚き", diff: "上級", file: "ochibataki_jo.png" },
  { season: "秋", genre: "風物詩", title: "読書の秋", diff: "上級", file: "dokusho_aki_jo.png" },
  { season: "秋", genre: "風物詩", title: "赤とんぼとすすき", diff: "中級", file: "akatonbo_susuki_chu.png" },
  { season: "秋", genre: "風景", title: "寺と彼岸花", diff: "上級", file: "tera_higanbana_jo.png" },
  { season: "秋", genre: "風景", title: "川辺のすすき", diff: "上級", file: "kawabe_susuki_jo.png" },
  // ---- 花(春) ----
  { season: "春", genre: "花", title: "つつじ", diff: "中級", file: "tsutsuji_chu.png" },
  { season: "春", genre: "花", title: "アネモネ", diff: "中級", file: "anemone_chu.png" },
  { season: "春", genre: "花", title: "カーネーション", diff: "中級", file: "carnation_chu.png" },
  { season: "春", genre: "花", title: "シャクナゲ", diff: "中級", file: "shakunage_chu.png" },
  { season: "春", genre: "花", title: "シャクヤク", diff: "中級", file: "shakuyaku_chu.png" },
  { season: "春", genre: "花", title: "チューリップ", diff: "中級", file: "tulip_chu.png" },
  { season: "春", genre: "花", title: "ネモフィラ", diff: "中級", file: "nemophila_chu.png" },
  { season: "春", genre: "花", title: "ハナミズキ", diff: "中級", file: "hanamizuki_chu.png" },
  { season: "春", genre: "花", title: "ボタン", diff: "中級", file: "botan_chu.png" },
  { season: "春", genre: "花", title: "マーガレット", diff: "中級", file: "marguerite_chu.png" },
  { season: "春", genre: "花", title: "モクレン", diff: "中級", file: "mokuren_chu.png" },
  { season: "春", genre: "花", title: "ラナンキュラス", diff: "中級", file: "ranunculus_chu.png" },
  { season: "春", genre: "花", title: "桜", diff: "中級", file: "sakura_chu.png" },
  { season: "春", genre: "花", title: "梅の花", diff: "中級", file: "ume_chu.png" },
  { season: "春", genre: "花", title: "芝桜", diff: "中級", file: "shibazakura_chu.png" },
  { season: "春", genre: "花", title: "花かんざし", diff: "中級", file: "hanakanzashi_chu.png" },
  { season: "春", genre: "花", title: "藤", diff: "中級", file: "fuji_hana_chu.png" },
  // ---- 花(夏) ----
  { season: "夏", genre: "花", title: "ペチュニア", diff: "中級", file: "petunia_chu.png" },
  { season: "夏", genre: "花", title: "マリーゴールド2", diff: "中級", file: "marigold2_chu.png" },
  { season: "夏", genre: "花", title: "マリーゴールド3", diff: "中級", file: "marigold3_chu.png" },
  { season: "夏", genre: "花", title: "ユリ", diff: "中級", file: "yuri2_chu.png" },
  { season: "夏", genre: "花", title: "ラベンダー2", diff: "中級", file: "lavender2_chu.png" },
  { season: "夏", genre: "花", title: "芙蓉", diff: "中級", file: "fuyou_chu.png" },
  // ---- 花(秋) ----
  { season: "秋", genre: "花", title: "シュウメイギク", diff: "中級", file: "shumeigiku_chu.png" },
  { season: "秋", genre: "花", title: "ネリネ", diff: "中級", file: "nerine_chu.png" },
  { season: "秋", genre: "花", title: "彼岸花", diff: "初級", file: "higanbana_sho.png" },
  { season: "秋", genre: "花", title: "皇帝ダリア", diff: "中級", file: "kotei_dahlia_chu.png" },
  // ---- 花(冬) ----
  { season: "冬", genre: "花", title: "カトレア", diff: "中級", file: "cattleya_chu.png" },
  { season: "冬", genre: "花", title: "クリスマスローズ", diff: "中級", file: "christmasrose_chu.png" },
  { season: "冬", genre: "花", title: "シクラメン", diff: "中級", file: "cyclamen_chu.png" },
  { season: "冬", genre: "花", title: "スイセン", diff: "初級", file: "suisen_sho.png" },
  { season: "冬", genre: "花", title: "スイセン", diff: "中級", file: "suisen_chu.png" },
  { season: "冬", genre: "花", title: "ツバキ", diff: "中級", file: "tsubaki_chu.png" },
  { season: "冬", genre: "花", title: "パンジー", diff: "中級", file: "pansy_chu.png" },
  { season: "冬", genre: "花", title: "プリムラ", diff: "中級", file: "primula_chu.png" },
  { season: "冬", genre: "花", title: "ポインセチア", diff: "中級", file: "poinsettia_chu.png" },
  { season: "冬", genre: "花", title: "山茶花", diff: "中級", file: "sazanka_chu.png" },
];
