// ============================================================
//  塗り絵・脳トレ・カレンダーの登録リスト
//  ※ このファイルは管理ページ(admin.html)から自動で更新されます。
// ============================================================

window.NURIE_LIST = [
  { season: "夏", genre: "花", title: "あじさい", diff: "中級", file: "ajisai_chu.png" },
  { season: "夏", genre: "花", title: "ひまわり", diff: "初級", file: "himawari_sho.png" },
  { season: "夏", genre: "花", title: "ひまわり", diff: "中級", file: "himawari_chu.png" },
  { season: "夏", genre: "花", title: "ひまわり", diff: "上級", file: "himawari_jo.png" },
  { season: "夏", genre: "花", title: "ひまわり畑", diff: "上級", file: "himawari_batake_jo.png" },
  { season: "夏", genre: "花", title: "ほおずき", diff: "中級", file: "hozuki_chu.png" },
  { season: "夏", genre: "花", title: "ゆり", diff: "中級", file: "yuri_chu.png" },
  { season: "夏", genre: "花", title: "アサガオ", diff: "中級", file: "asagao_chu.png" },
  { season: "夏", genre: "花", title: "オシロイバナ", diff: "中級", file: "oshiroibana_chu.png" },
  { season: "夏", genre: "花", title: "クチナシ", diff: "中級", file: "kuchinashi_chu.png" },
  { season: "夏", genre: "花", title: "スイレン", diff: "中級", file: "suiren_chu.png" },
  { season: "夏", genre: "花", title: "ダリア", diff: "中級", file: "dahlia_chu.png" },
  { season: "夏", genre: "花", title: "ノウゼンカズラ", diff: "中級", file: "nouzenkazura_chu.png" },
  { season: "夏", genre: "花", title: "ハイビスカス", diff: "中級", file: "hibiscus_chu.png" },
  { season: "夏", genre: "花", title: "ハナショウブ", diff: "中級", file: "hanashobu_chu.png" },
  { season: "夏", genre: "花", title: "マリーゴールド", diff: "中級", file: "marigold_chu.png" },
  { season: "夏", genre: "花", title: "ラベンダー", diff: "中級", file: "lavender_chu.png" },
  { season: "夏", genre: "花", title: "百日紅", diff: "中級", file: "sarusuberi_chu.png" },
  { season: "夏", genre: "花", title: "蓮", diff: "中級", file: "hasu_chu.png" },
  { season: "夏", genre: "食べ物", title: "かき氷", diff: "初級", file: "kakigori_sho.png" },
  { season: "夏", genre: "食べ物", title: "すいか", diff: "初級", file: "suika_sho.png" },
  { season: "夏", genre: "食べ物", title: "夏の果物", diff: "初級", file: "natsu_kudamono_sho.png" },
  { season: "夏", genre: "食べ物", title: "夏野菜", diff: "初級", file: "natsu_yasai_sho.png" },
  { season: "夏", genre: "食べ物", title: "夏野菜", diff: "中級", file: "natsu_yasai_chu.png" },
  { season: "夏", genre: "食べ物", title: "夏野菜", diff: "上級", file: "natsu_yasai_jo.png" },
  { season: "夏", genre: "食べ物", title: "とうもろこし", diff: "初級", file: "toumorokoshi_sho.png" },
  { season: "夏", genre: "風物詩", title: "うちわ", diff: "初級", file: "uchiwa_sho.png" },
  { season: "夏", genre: "風物詩", title: "うちわと金魚鉢", diff: "初級", file: "uchiwa_kingyo_sho.png" },
  { season: "夏", genre: "風物詩", title: "すだれ風鈴", diff: "中級", file: "sudare_furin_chu.png" },
  { season: "夏", genre: "風物詩", title: "すだれ風鈴", diff: "上級", file: "sudare_furin_jo.png" },
  { season: "夏", genre: "行事", title: "よーよーつり", diff: "初級", file: "yoyo_tsuri_sho.png" },
  { season: "夏", genre: "行事", title: "よーよーつり", diff: "中級", file: "yoyo_tsuri_chu.png" },
  { season: "夏", genre: "行事", title: "夏まつり", diff: "上級", file: "natsu_matsuri_jo.png" },
  { season: "夏", genre: "行事", title: "夏祭り", diff: "初級", file: "natsu_matsuri_sho.png" },
  { season: "夏", genre: "行事", title: "夏祭り", diff: "中級", file: "natsu_matsuri_chu.png" },
  { season: "夏", genre: "行事", title: "祇園祭", diff: "上級", file: "gion_matsuri_jo.png" },
  { season: "夏", genre: "行事", title: "精霊馬", diff: "初級", file: "shoryo_uma_sho.png" },
  { season: "夏", genre: "行事", title: "精霊馬", diff: "上級", file: "shoryo_uma_jo.png" },
  { season: "夏", genre: "行事", title: "花火", diff: "中級", file: "hanabi_chu.png" },
  { season: "夏", genre: "行事", title: "花火", diff: "上級", file: "hanabi_jo.png" },
  { season: "夏", genre: "行事", title: "金魚すくい", diff: "中級", file: "kingyo_sukui_chu.png" },
  { season: "夏", genre: "風景", title: "夏", diff: "初級", file: "natsu_sho.png" },
  { season: "夏", genre: "風景", title: "夏", diff: "中級", file: "natsu_chu.png" },
  { season: "夏", genre: "風景", title: "夏", diff: "上級", file: "natsu_jo.png" },
  { season: "夏", genre: "風景", title: "夏の海", diff: "中級", file: "natsu_umi_chu.png" },
  { season: "夏", genre: "風景", title: "夏の海", diff: "上級", file: "natsu_umi_jo.png" },
  { season: "夏", genre: "動物", title: "蝉取り", diff: "中級", file: "semitori_chu.png" },
  { season: "通年", genre: "動物", title: "うさぎ", diff: "初級", file: "usagi_sho.png" },
  { season: "通年", genre: "動物", title: "うさぎ", diff: "中級", file: "usagi_chu.png" },
  { season: "通年", genre: "動物", title: "くじら", diff: "中級", file: "kujira_chu.png" },
  { season: "通年", genre: "動物", title: "しば犬", diff: "中級", file: "shibainu_chu.png" },
  { season: "通年", genre: "動物", title: "しば犬と猫", diff: "上級", file: "shibainu_neko_jo.png" },
  { season: "通年", genre: "動物", title: "ふくろう", diff: "中級", file: "fukurou_chu.png" },
  { season: "通年", genre: "動物", title: "アヒル", diff: "初級", file: "ahiru_sho.png" },
  { season: "通年", genre: "動物", title: "インコ", diff: "中級", file: "inko_chu.png" },
  { season: "通年", genre: "動物", title: "サバンナ", diff: "上級", file: "savanna_jo.png" },
  { season: "通年", genre: "動物", title: "ハムスター", diff: "初級", file: "hamster_sho.png" },
  { season: "通年", genre: "動物", title: "動物園", diff: "初級", file: "doubutsuen_sho.png" },
  { season: "通年", genre: "動物", title: "動物園", diff: "上級", file: "doubutsuen_jo.png" },
  { season: "通年", genre: "動物", title: "海の生き物", diff: "初級", file: "umi_ikimono_sho.png" },
  { season: "通年", genre: "動物", title: "海の生き物 その2", diff: "初級", file: "umi_ikimono_sho_2.png" },
  { season: "通年", genre: "動物", title: "熊", diff: "初級", file: "kuma_sho.png" },
  { season: "通年", genre: "動物", title: "犬", diff: "初級", file: "inu_sho.png" },
  { season: "通年", genre: "動物", title: "犬", diff: "中級", file: "inu_chu.png" },
  { season: "通年", genre: "動物", title: "犬と猫", diff: "初級", file: "inu_neko_sho.png" },
  { season: "通年", genre: "動物", title: "犬と猫", diff: "中級", file: "inu_neko_chu.png" },
  { season: "通年", genre: "動物", title: "犬と猫", diff: "上級", file: "inu_neko_jo.png" },
  { season: "通年", genre: "動物", title: "犬種", diff: "初級", file: "inushu_sho.png" },
  { season: "通年", genre: "動物", title: "狼", diff: "初級", file: "ookami_sho.png" },
  { season: "通年", genre: "動物", title: "狼", diff: "上級", file: "ookami_jo.png" },
  { season: "通年", genre: "動物", title: "猫", diff: "初級", file: "neko_sho.png" },
  { season: "通年", genre: "動物", title: "猫", diff: "中級", file: "neko_chu.png" },
  { season: "通年", genre: "動物", title: "猫", diff: "上級", file: "neko_jo.png" },
  { season: "通年", genre: "動物", title: "猫カフェ", diff: "上級", file: "neko_cafe_jo.png" },
  { season: "通年", genre: "動物", title: "羊", diff: "中級", file: "hitsuji_chu.png" },
  { season: "通年", genre: "動物", title: "羊", diff: "上級", file: "hitsuji_jo.png" },
  { season: "通年", genre: "動物", title: "蝶を追いかける猫", diff: "中級", file: "chou_neko_chu.png" },
  { season: "通年", genre: "動物", title: "金魚", diff: "上級", file: "kingyo_jo.png" },
  { season: "通年", genre: "動物", title: "馬", diff: "中級", file: "uma_chu.png" },
  { season: "通年", genre: "動物", title: "馬", diff: "上級", file: "uma_jo.png" },
  { season: "通年", genre: "動物", title: "庭の猫", diff: "上級", file: "niwa_neko.png" },
  { season: "通年", genre: "風景", title: "田園風景", diff: "上級", file: "denen_fukei.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字(魚へん)", diff: "中級", file: "nandoku_kanji_sakana.png", answer: "nandoku_kanji_sakana_kotae.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ絵クイズ その1", diff: "中級", file: "kotowaza_quiz_1.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ絵クイズ その2", diff: "中級", file: "kotowaza_quiz_2.png" },
  { kind: "カレンダー", year: 2026, month: 8, season: "通年", title: "8月カレンダー", file: "calendar_2026_08.png" },
  { kind: "カレンダー", year: 2026, month: 8, season: "通年", title: "8月カレンダー(貼り付け用)", file: "calendar_2026_08_blank.png" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー", file: "calendar_2026_09.png" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー5", file: "calendar_2026_09_2.png" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー(貼り付け用)", file: "calendar_2026_09_blank.png" },
  { kind: "カレンダー", year: 2026, month: 10, season: "通年", title: "10月カレンダー(貼り付け用)", file: "calendar_2026_10_blank.png" },
  { season: "秋", genre: "花", title: "きんもくせい", diff: "中級", file: "kinmokusei_chu.png" },
  { season: "秋", genre: "花", title: "コスモス", diff: "初級", file: "cosmos_sho.png" },
  { season: "秋", genre: "花", title: "コスモス", diff: "中級", file: "cosmos_chu.png" },
  { season: "秋", genre: "花", title: "コスモス", diff: "上級", file: "cosmos_jo.png" },
  { season: "秋", genre: "花", title: "コスモス2", diff: "初級", file: "cosmos2_sho.png" },
  { season: "秋", genre: "花", title: "コスモス2", diff: "中級", file: "cosmos2_chu.png" },
  { season: "秋", genre: "花", title: "コスモス3", diff: "中級", file: "cosmos3_chu.png" },
  { season: "秋", genre: "花", title: "サフラン", diff: "中級", file: "saffron_chu.png" },
  { season: "秋", genre: "花", title: "ダリア", diff: "中級", file: "dahlia_aki_chu.png" },
  { season: "秋", genre: "花", title: "バラ", diff: "中級", file: "bara_aki_chu.png" },
  { season: "秋", genre: "花", title: "ホトトギス", diff: "中級", file: "hototogisu_chu.png" },
  { season: "秋", genre: "花", title: "リンドウ", diff: "中級", file: "rindou_chu.png" },
  { season: "秋", genre: "花", title: "孔雀草", diff: "中級", file: "kujakusou_chu.png" },
  { season: "秋", genre: "花", title: "桔梗", diff: "中級", file: "kikyou_chu.png" },
  { season: "秋", genre: "花", title: "秋の七草", diff: "中級", file: "aki_nanakusa_chu.png" },
  { season: "秋", genre: "花", title: "菊", diff: "中級", file: "kiku_aki_chu.png" },
  { season: "秋", genre: "食べ物", title: "おでん", diff: "初級", file: "oden_sho.png" },
  { season: "秋", genre: "食べ物", title: "おはぎ", diff: "中級", file: "ohagi_chu.png" },
  { season: "秋", genre: "食べ物", title: "さんまの塩焼き", diff: "初級", file: "sanma_shioyaki_sho.png" },
  { season: "秋", genre: "食べ物", title: "ぶどうと梨", diff: "中級", file: "budou_nashi_chu.png" },
  { season: "秋", genre: "食べ物", title: "みかんとりんご", diff: "初級", file: "mikan_ringo_sho.png" },
  { season: "秋", genre: "食べ物", title: "千歳飴", diff: "初級", file: "chitoseame_sho.png" },
  { season: "秋", genre: "食べ物", title: "干し柿", diff: "初級", file: "hoshigaki_sho.png" },
  { season: "秋", genre: "食べ物", title: "柿", diff: "初級", file: "kaki_sho.png" },
  { season: "秋", genre: "食べ物", title: "栗ご飯", diff: "初級", file: "kurigohan_sho.png" },
  { season: "秋", genre: "食べ物", title: "焼き芋", diff: "中級", file: "yakiimo_chu.png" },
  { season: "秋", genre: "食べ物", title: "秋のキノコ", diff: "初級", file: "aki_kinoko_sho.png" },
  { season: "秋", genre: "食べ物", title: "秋の味覚", diff: "上級", file: "aki_mikaku_jo.png" },
  { season: "秋", genre: "食べ物", title: "銀杏", diff: "初級", file: "ginnan_sho.png" },
  { season: "秋", genre: "行事", title: "お彼岸", diff: "上級", file: "ohigan_jo.png" },
  { season: "秋", genre: "行事", title: "お月見", diff: "中級", file: "otsukimi_chu.png" },
  { season: "秋", genre: "行事", title: "だんじり祭り", diff: "上級", file: "danjiri_jo.png" },
  { season: "秋", genre: "行事", title: "ハロウィン", diff: "中級", file: "halloween_chu.png" },
  { season: "秋", genre: "行事", title: "ハロウィン", diff: "上級", file: "halloween_jo.png" },
  { season: "秋", genre: "行事", title: "七五三", diff: "上級", file: "shichigosan_jo.png" },
  { season: "秋", genre: "行事", title: "中秋の名月", diff: "上級", file: "chushu_meigetsu_jo.png" },
  { season: "秋", genre: "行事", title: "敬老の日", diff: "中級", file: "keirou_chu.png" },
  { season: "秋", genre: "行事", title: "敬老の日", diff: "上級", file: "keirou_jo.png" },
  { season: "秋", genre: "行事", title: "文化の日", diff: "中級", file: "bunka_no_hi_chu.png" },
  { season: "秋", genre: "行事", title: "月見", diff: "初級", file: "tsukimi1_sho.png" },
  { season: "秋", genre: "行事", title: "月見2", diff: "初級", file: "tsukimi2_sho.png" },
  { season: "秋", genre: "行事", title: "月見のうさぎ", diff: "中級", file: "tsukimi_usagi_chu.png" },
  { season: "秋", genre: "行事", title: "紅葉狩り", diff: "初級", file: "momijigari_sho.png" },
  { season: "秋", genre: "行事", title: "紅葉狩り", diff: "上級", file: "momijigari_jo.png" },
  { season: "秋", genre: "行事", title: "芋ほり", diff: "上級", file: "imohori_jo.png" },
  { season: "秋", genre: "行事", title: "運動会", diff: "上級", file: "undoukai_aki_jo.png" },
  { season: "秋", genre: "風物詩", title: "いちょう", diff: "上級", file: "icho_jo.png" },
  { season: "秋", genre: "風物詩", title: "すずむし", diff: "中級", file: "suzumushi_chu.png" },
  { season: "秋", genre: "風物詩", title: "どんぐりとまつぼっくり", diff: "初級", file: "donguri_matsubokkuri_sho.png" },
  { season: "秋", genre: "風物詩", title: "焼き芋屋", diff: "中級", file: "yakiimoya_chu.png" },
  { season: "秋", genre: "風物詩", title: "白露", diff: "中級", file: "hakuro_chu.png" },
  { season: "秋", genre: "風物詩", title: "白露2", diff: "中級", file: "hakuro2_chu.png" },
  { season: "秋", genre: "風物詩", title: "稲刈り", diff: "上級", file: "inekari_jo.png" },
  { season: "秋", genre: "風物詩", title: "稲刈り2", diff: "上級", file: "inekari2_jo.png" },
  { season: "秋", genre: "風物詩", title: "紅葉", diff: "中級", file: "kouyou_chu.png" },
  { season: "秋", genre: "風物詩", title: "落ち葉焚き", diff: "上級", file: "ochibataki_jo.png" },
  { season: "秋", genre: "風物詩", title: "読書の秋", diff: "上級", file: "dokusho_aki_jo.png" },
  { season: "秋", genre: "風物詩", title: "赤とんぼとすすき", diff: "中級", file: "akatonbo_susuki_chu.png" },
  { season: "秋", genre: "風景", title: "寺と彼岸花", diff: "上級", file: "tera_higanbana_jo.png" },
  { season: "秋", genre: "風景", title: "川辺のすすき", diff: "上級", file: "kawabe_susuki_jo.png" },
  { season: "春", genre: "花", title: "つつじ", diff: "中級", file: "tsutsuji_chu.png" },
  { season: "春", genre: "花", title: "アネモネ", diff: "中級", file: "anemone_chu.png" },
  { season: "春", genre: "花", title: "カーネーション", diff: "中級", file: "carnation_chu.png" },
  { season: "春", genre: "花", title: "シャクナゲ", diff: "中級", file: "shakunage_chu.png" },
  { season: "春", genre: "花", title: "シャクヤク", diff: "中級", file: "shakuyaku_chu.png" },
  { season: "春", genre: "花", title: "チューリップ", diff: "中級", file: "tulip_chu.png" },
  { season: "春", genre: "花", title: "ネモフィラ", diff: "中級", file: "nemophila_chu.png" },
  { season: "春", genre: "花", title: "ハナミズキ", diff: "中級", file: "hanamizuki_chu.png" },
  { season: "春", genre: "花", title: "ボタン", diff: "中級", file: "botan_chu.png" },
  { season: "春", genre: "花", title: "マーガレット", diff: "中級", file: "marguerite_chu.png" },
  { season: "春", genre: "花", title: "モクレン", diff: "中級", file: "mokuren_chu.png" },
  { season: "春", genre: "花", title: "ラナンキュラス", diff: "中級", file: "ranunculus_chu.png" },
  { season: "春", genre: "花", title: "桜", diff: "中級", file: "sakura_chu.png" },
  { season: "春", genre: "花", title: "梅の花", diff: "中級", file: "ume_chu.png" },
  { season: "春", genre: "花", title: "芝桜", diff: "中級", file: "shibazakura_chu.png" },
  { season: "春", genre: "花", title: "花かんざし", diff: "中級", file: "hanakanzashi_chu.png" },
  { season: "春", genre: "花", title: "藤", diff: "中級", file: "fuji_hana_chu.png" },
  { season: "夏", genre: "花", title: "ペチュニア", diff: "中級", file: "petunia_chu.png" },
  { season: "夏", genre: "花", title: "マリーゴールド2", diff: "中級", file: "marigold2_chu.png" },
  { season: "夏", genre: "花", title: "マリーゴールド3", diff: "中級", file: "marigold3_chu.png" },
  { season: "夏", genre: "花", title: "ユリ", diff: "中級", file: "yuri2_chu.png" },
  { season: "夏", genre: "花", title: "ラベンダー2", diff: "中級", file: "lavender2_chu.png" },
  { season: "夏", genre: "花", title: "芙蓉", diff: "中級", file: "fuyou_chu.png" },
  { season: "秋", genre: "花", title: "シュウメイギク", diff: "中級", file: "shumeigiku_chu.png" },
  { season: "秋", genre: "花", title: "ネリネ", diff: "中級", file: "nerine_chu.png" },
  { season: "秋", genre: "花", title: "彼岸花", diff: "初級", file: "higanbana_sho.png" },
  { season: "秋", genre: "花", title: "皇帝ダリア", diff: "中級", file: "kotei_dahlia_chu.png" },
  { season: "冬", genre: "花", title: "カトレア", diff: "中級", file: "cattleya_chu.png" },
  { season: "冬", genre: "花", title: "クリスマスローズ", diff: "中級", file: "christmasrose_chu.png" },
  { season: "冬", genre: "花", title: "シクラメン", diff: "中級", file: "cyclamen_chu.png" },
  { season: "冬", genre: "花", title: "スイセン", diff: "初級", file: "suisen_sho.png" },
  { season: "冬", genre: "花", title: "スイセン", diff: "中級", file: "suisen_chu.png" },
  { season: "冬", genre: "花", title: "ツバキ", diff: "中級", file: "tsubaki_chu.png" },
  { season: "冬", genre: "花", title: "パンジー", diff: "中級", file: "pansy_chu.png" },
  { season: "冬", genre: "花", title: "プリムラ", diff: "中級", file: "primula_chu.png" },
  { season: "冬", genre: "花", title: "ポインセチア", diff: "中級", file: "poinsettia_chu.png" },
  { season: "冬", genre: "花", title: "山茶花", diff: "中級", file: "sazanka_chu.png" },
  { season: "秋", genre: "食べ物", title: "新米", diff: "初級", file: "shinmai_sho.png" },
  { season: "秋", genre: "風景", title: "秋", diff: "初級", file: "aki_fukei_sho.png" },
  { season: "秋", genre: "風景", title: "秋", diff: "上級", file: "aki_fukei_jo.png" },
  { season: "冬", genre: "行事", title: "ゆず湯", diff: "中級", file: "yuzuyu_chu.png" },
  { season: "冬", genre: "行事", title: "クリスマス", diff: "初級", file: "christmas_sho.png" },
  { season: "冬", genre: "行事", title: "クリスマス", diff: "上級", file: "christmas_jo.png" },
  { season: "冬", genre: "食べ物", title: "クリスマスケーキ", diff: "初級", file: "christmas_cake_sho.png" },
  { season: "冬", genre: "行事", title: "サンタクロース", diff: "中級", file: "santa_chu.png" },
  { season: "冬", genre: "風物詩", title: "マフラーと手袋", diff: "初級", file: "muffler_tebukuro_sho.png" },
  { season: "冬", genre: "風景", title: "冬", diff: "中級", file: "fuyu_fukei_chu.png" },
  { season: "冬", genre: "行事", title: "冬至", diff: "上級", file: "touji_jo.png" },
  { season: "冬", genre: "行事", title: "大掃除", diff: "中級", file: "osouji_chu.png" },
  { season: "冬", genre: "食べ物", title: "年越しそば", diff: "初級", file: "toshikoshi_soba_sho.png" },
  { season: "冬", genre: "行事", title: "正月", diff: "初級", file: "shogatsu_sho.png" },
  { season: "冬", genre: "行事", title: "正月", diff: "中級", file: "shogatsu_chu.png" },
  { season: "冬", genre: "食べ物", title: "鍋", diff: "中級", file: "nabe_chu.png" },
  { season: "冬", genre: "行事", title: "餅つき", diff: "中級", file: "mochitsuki_chu.png" },
  { season: "通年", genre: "動物", title: "鯉", diff: "初級", file: "koi_sho.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "3文字しりとり", diff: "初級", file: "up_1785644279674_1.png", answer: "up_1785644282058_2.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 野菜編", diff: "中級", file: "nandoku_yasai.png", answer: "nandoku_yasai_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 果物編", diff: "中級", file: "nandoku_kudamono.png", answer: "nandoku_kudamono_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 動物編", diff: "中級", file: "nandoku_doubutsu.png", answer: "nandoku_doubutsu_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "四字熟語 穴埋め", diff: "中級", file: "yojijukugo.png", answer: "yojijukugo_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "反対語クイズ", diff: "初級", file: "hantaigo.png", answer: "hantaigo_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "穴あき言葉 食べ物編", diff: "初級", file: "anaaki_tabemono.png", answer: "anaaki_tabemono_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "計算", title: "虫食い算", diff: "初級", file: "mushikuizan.png", answer: "mushikuizan_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 花編", diff: "中級", file: "nandoku_hana.png", answer: "nandoku_hana_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 国名編", diff: "上級", file: "nandoku_kokumei.png", answer: "nandoku_kokumei_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ穴埋め その2", diff: "初級", file: "kotowaza_anaume2.png", answer: "kotowaza_anaume2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "計算", title: "お買い物計算", diff: "初級", file: "okaimono_keisan.png", answer: "okaimono_keisan_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "仲間はずれ探し", diff: "初級", file: "nakamahazure.png", answer: "nakamahazure_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "逆さ言葉クイズ", diff: "初級", file: "sakasa_kotoba.png", answer: "sakasa_kotoba_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "昔の言葉クイズ", file: "mukashi_kotoba.png", answer: "mukashi_kotoba_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "慣用句 体の部分編", file: "kanyoku_karada.png", answer: "kanyoku_karada_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "漢字の足し算", file: "kanji_tashizan.png", answer: "kanji_tashizan_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "穴あき言葉 動物編", file: "anaaki_doubutsu.png", answer: "anaaki_doubutsu_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "都道府県クイズ", file: "todofuken_quiz.png", answer: "todofuken_quiz_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "計算", title: "虫食い算 その2", file: "mushikuizan2.png", answer: "mushikuizan2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 鳥編", file: "nandoku_tori.png", answer: "nandoku_tori_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 虫編", file: "nandoku_mushi.png", answer: "nandoku_mushi_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 道具編", file: "nandoku_dogu.png", answer: "nandoku_dogu_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "数字探し 1〜30", file: "suuji_sagashi30.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "数字探し 1〜50", file: "suuji_sagashi50.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "時計クイズ", file: "tokei_quiz.png", answer: "tokei_quiz_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "2文字しりとり", file: "shiritori_2moji.png", answer: "shiritori_2moji_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "3文字しりとり その2", file: "shiritori_3moji2.png", answer: "shiritori_3moji2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "4文字しりとり", file: "shiritori_4moji.png", answer: "shiritori_4moji_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "並び替えクイズ 4文字", file: "narabekae_4moji.png", answer: "narabekae_4moji_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "並び替えクイズ 5文字", file: "narabekae_5moji.png", answer: "narabekae_5moji_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "並び替えクイズ 4文字 その2", file: "narabekae_4moji2.png", answer: "narabekae_4moji2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "並び替えクイズ 4文字 その3", file: "narabekae_4moji3.png", answer: "narabekae_4moji3_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "並び替えクイズ 5文字 その2", file: "narabekae_5moji2.png", answer: "narabekae_5moji2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "並び替えクイズ 5文字 その3", file: "narabekae_5moji3.png", answer: "narabekae_5moji3_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "ことばさがし くだもの", file: "kotoba_kudamono.png", answer: "kotoba_kudamono_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "ことばさがし どうぶつ", file: "kotoba_doubutsu.png", answer: "kotoba_doubutsu_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "ことばさがし やさい", file: "kotoba_yasai.png", answer: "kotoba_yasai_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "四字熟語ことばさがし その1", file: "yoji_sagashi1.png", answer: "yoji_sagashi1_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "四字熟語ことばさがし その2", file: "yoji_sagashi2.png", answer: "yoji_sagashi2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "熟語パズル その1", file: "jukugo_puzzle1.png", answer: "jukugo_puzzle1_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "熟語パズル その2", file: "jukugo_puzzle2.png", answer: "jukugo_puzzle2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "熟語パズル その3", file: "jukugo_puzzle3.png", answer: "jukugo_puzzle3_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "熟語パズル その4", file: "jukugo_puzzle4.png", answer: "jukugo_puzzle4_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "四字熟語ジグザグ その1", file: "zigzag1.png", answer: "zigzag1_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "四字熟語ジグザグ その2", file: "zigzag2.png", answer: "zigzag2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "昭和の大スター穴埋め 歌手編", file: "showa_star_kashu.png", answer: "showa_star_kashu_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "漢字の足し算 その2", file: "kanji_tashizan2.png", answer: "kanji_tashizan2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "漢字の足し算 その3", file: "kanji_tashizan3.png", answer: "kanji_tashizan3_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ穴埋め 動物編", diff: "初級", file: "kotowaza_doubutsu.png", answer: "kotowaza_doubutsu_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "計算", title: "虫食い算 その3", file: "mushikuizan3.png", answer: "mushikuizan3_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "計算", title: "虫食い算 その4", file: "mushikuizan4.png", answer: "mushikuizan4_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "ことわざ", title: "ことわざ穴埋め その3", file: "kotowaza_anaume3.png", answer: "kotowaza_anaume3_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "反対語クイズ その2", file: "hantaigo2.png", answer: "hantaigo2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "穴あき言葉 乗り物編", file: "anaaki_norimono.png", answer: "anaaki_norimono_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "逆さ言葉クイズ その2", file: "sakasa_kotoba2.png", answer: "sakasa_kotoba2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "言葉遊び", title: "仲間はずれ探し その2", file: "nakamahazure2.png", answer: "nakamahazure2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "昔の言葉クイズ その2", file: "mukashi_kotoba2.png", answer: "mukashi_kotoba2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "計算", title: "お買い物計算 その2", file: "okaimono_keisan2.png", answer: "okaimono_keisan2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "クイズ", title: "都道府県クイズ その2", file: "todofuken_quiz2.png", answer: "todofuken_quiz2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "四字熟語 穴埋め その2", file: "yojijukugo2.png", answer: "yojijukugo2_ans.png" },
  { kind: "脳トレ", season: "通年", genre: "漢字", title: "難読漢字 天気編", file: "nandoku_tenki.png", answer: "nandoku_tenki_ans.png" },
  { season: "夏", genre: "花", title: "アジサイと傘", diff: "中級", file: "ajisai_kasa_chu.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "カニ", diff: "初級", file: "kani_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "こいのぼり", diff: "初級", file: "koinobori_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "こたつとみかん", diff: "上級", file: "kotatsu_mikan_jo.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "さくらもち", diff: "初級", file: "sakuramochi_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "サンタクロース", diff: "中級", file: "santa_claus_chu.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "ししまいと門松", diff: "中級", file: "shishimai_kadomatsu_chu.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "たけのこ", diff: "初級", file: "takenoko_sho.png", added: "2026-08" },
  { season: "春", genre: "風物詩", title: "たけのこ掘り", diff: "上級", file: "takenoko_hori_jo.png", added: "2026-08" },
  { season: "春", genre: "花", title: "たんぽぽと蝶", diff: "中級", file: "tanpopo_chou_chu.png", added: "2026-08" },
  { season: "春", genre: "花", title: "ちゅーりっぷとてんとうむし", diff: "初級", file: "tulip_tentomushi_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "ちゅーりっぷとてんとうむし", diff: "中級", file: "tulip_tentomushi_chu.png", added: "2026-08" },
  { season: "春", genre: "花", title: "つくしとたんぽぽ", diff: "初級", file: "tsukushi_tanpopo_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "ひなまつり", diff: "初級", file: "hinamatsuri_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "ゆきだるま", diff: "初級", file: "yukidaruma_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "リース", diff: "初級", file: "wreath_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "囲炉裏", diff: "中級", file: "irori_chu.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "羽子板", diff: "中級", file: "hagoita_chu.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "雨の日", diff: "中級", file: "ame_no_hi_chu.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "温泉", diff: "初級", file: "onsen_sho.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "河川敷の桜", diff: "上級", file: "kasenjiki_sakura_jo.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "河川敷の桜", diff: "中級", file: "kasenjiki_sakura_chu.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "菊人形", diff: "上級", file: "kikuningyo_jo.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "鏡もちと門松", diff: "中級", file: "kagamimochi_kadomatsu_chu.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "蛍", diff: "中級", file: "hotaru_chu.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "蛍狩り", diff: "上級", file: "hotarugari_jo.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "七草", diff: "初級", file: "nanakusa_sho.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "七夕", diff: "中級", file: "tanabata_chu.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "秋の動物たち", diff: "上級", file: "aki_doubutsu_jo.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "春の食材", diff: "初級", file: "haru_shokuzai_sho.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "春の田舎", diff: "上級", file: "haru_inaka_jo.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "初詣", diff: "上級", file: "hatsumoude_jo.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "除夜の鐘", diff: "上級", file: "joya_no_kane_jo.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "正月", diff: "上級", file: "shogatsu_jo.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "正月の遊び", diff: "初級", file: "shogatsu_asobi_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "節分", diff: "初級", file: "setsubun_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "節分", diff: "中級", file: "setsubun_chu.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "暖炉", diff: "初級", file: "danro_sho.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "冬の食材", diff: "初級", file: "fuyu_shokuzai_sho.png", added: "2026-08" },
  { season: "冬", genre: "動物", title: "冬の動物たち", diff: "中級", file: "fuyu_doubutsu_chu.png", added: "2026-08" },
  { season: "春", genre: "花", title: "藤棚", diff: "上級", file: "fujidana_jo.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "梅雨", diff: "上級", file: "tsuyu_jo.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "餅", diff: "上級", file: "mochi_jo.png", added: "2026-08" },
  { season: "夏", genre: "花", title: "あじさい その2", diff: "中級", file: "ajisai2_chu.png", added: "2026-08" },
  { season: "春", genre: "風物詩", title: "いちご狩り", diff: "中級", file: "ichigogari_chu.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "お花見", diff: "上級", file: "ohanami_jo.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "お雑煮", diff: "初級", file: "ozouni_sho.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "かしわもち", diff: "初級", file: "kashiwamochi_sho.png", added: "2026-08" },
  { season: "冬", genre: "動物", title: "かまくらの中の猫", diff: "初級", file: "kamakura_neko_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "こいのぼり", diff: "上級", file: "koinobori_jo.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "こどもの日", diff: "初級", file: "kodomonohi_sho.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "さくらもち その2", diff: "初級", file: "sakuramochi2_sho.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "シチュー", diff: "初級", file: "stew_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "スキー場", diff: "中級", file: "skijo_chu.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "すすきとうさぎ", diff: "初級", file: "susuki_usagi_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "スノードーム", diff: "初級", file: "snowdome_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "たんぽぽ", diff: "中級", file: "tanpopo_chu.png", added: "2026-08" },
  { season: "春", genre: "花", title: "ちゅーりっぷとうさぎ", diff: "初級", file: "tulip_usagi_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "ハロウィン その2", diff: "上級", file: "halloween2_jo.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "ひなまつり その2", diff: "初級", file: "hinamatsuri2_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "マフラー", diff: "初級", file: "muffler_sho.png", added: "2026-08" },
  { season: "春", genre: "動物", title: "メジロ", diff: "中級", file: "mejiro_chu.png", added: "2026-08" },
  { season: "春", genre: "動物", title: "もぐらとつくし", diff: "中級", file: "mogura_tsukushi_chu.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "一本桜", diff: "上級", file: "ipponzakura_jo.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "雨の縁側", diff: "中級", file: "ame_engawa_chu.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "夏のバス停", diff: "上級", file: "natsu_basutei_jo.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "夏の縁側", diff: "上級", file: "natsu_engawa_jo.png", added: "2026-08" },
  { season: "夏", genre: "動物", title: "夏の昆虫", diff: "初級", file: "natsu_konchu_sho.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "夏休み", diff: "初級", file: "natsuyasumi_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "花冠", diff: "中級", file: "hanakanmuri_chu.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "熊とリス", diff: "中級", file: "kuma_risu_chu.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "栗", diff: "初級", file: "kuri_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "建国記念の日", diff: "初級", file: "kenkoku_kinenbi_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "元旦", diff: "初級", file: "gantan_sho.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "紅葉", diff: "初級", file: "kouyou_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "菜の花", diff: "中級", file: "nanohana_chu.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "桜の木", diff: "初級", file: "sakura_ki_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "四葉とてんとうむし", diff: "初級", file: "yotsuba_tentomushi_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "師走", diff: "中級", file: "shiwasu_chu.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "収穫", diff: "上級", file: "shukaku_jo.png", added: "2026-08" },
  { season: "秋", genre: "風景", title: "収穫期のたんぼ", diff: "中級", file: "shukakuki_tanbo_chu.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "秋ナス", diff: "初級", file: "akinasu_sho.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "秋のきつね", diff: "中級", file: "aki_kitsune_chu.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "秋のリス", diff: "中級", file: "aki_risu_chu.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "秋の果物", diff: "初級", file: "aki_kudamono_sho.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "秋の俳句", diff: "初級", file: "aki_haiku_sho.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "秋の葉っぱ", diff: "初級", file: "aki_happa_sho.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "春の越前大野城", diff: "中級", file: "haru_onojo_chu.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "春の散歩", diff: "上級", file: "haru_sanpo_jo.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "春の味覚", diff: "初級", file: "haru_mikaku_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "初日の出", diff: "中級", file: "hatsuhinode_chu.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "松茸", diff: "初級", file: "matsutake_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "菖蒲湯", diff: "中級", file: "shobuyu_chu.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "新嘗祭", diff: "中級", file: "niinamesai_chu.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "成人の日", diff: "初級", file: "seijin_no_hi_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "成人式", diff: "中級", file: "seijinshiki_chu.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "赤とんぼ", diff: "初級", file: "akatonbo_sho.png", added: "2026-08" },
  { season: "冬", genre: "動物", title: "雪だるまと犬", diff: "初級", file: "yukidaruma_inu_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "雪だるま作り", diff: "初級", file: "yukidaruma_zukuri_sho.png", added: "2026-08" },
  { season: "夏", genre: "食べ物", title: "川で冷やした夏野菜", diff: "中級", file: "kawa_natsuyasai_chu.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "天皇誕生日", diff: "初級", file: "tennou_tanjobi_sho.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "電車と桜", diff: "上級", file: "densha_sakura_jo.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬のかやぶきの里", diff: "上級", file: "fuyu_kayabuki_jo.png", added: "2026-08" },
  { season: "冬", genre: "動物", title: "冬のきつね", diff: "中級", file: "fuyu_kitsune_chu.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬の縁側", diff: "上級", file: "fuyu_engawa_jo.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬の金閣寺", diff: "中級", file: "fuyu_kinkakuji_chu.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬の小屋", diff: "初級", file: "fuyu_koya_sho.png", added: "2026-08" },
  { season: "冬", genre: "動物", title: "冬の動物", diff: "初級", file: "fuyu_doubutsu_sho.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "読書の秋", diff: "初級", file: "dokusho_aki_sho.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "肉まん", diff: "初級", file: "nikuman_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "入学式", diff: "上級", file: "nyugakushiki_jo.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "梅雨の合唱", diff: "初級", file: "tsuyu_gassho_sho.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "麦わら帽子ととんぼ", diff: "中級", file: "mugiwara_tonbo_chu.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "餅", diff: "初級", file: "mochi_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "ゆず湯", diff: "初級", file: "yuzuyu_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "ゆず湯 その2", diff: "初級", file: "yuzuyu2_sho.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "落ち葉", diff: "初級", file: "ochiba_sho.png", added: "2026-08" },
  { season: "夏", genre: "食べ物", title: "冷やし中華", diff: "初級", file: "hiyashi_chuka_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "芍薬と牡丹", diff: "中級", file: "shakuyaku_botan_chu.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "いちょうと狐", diff: "上級", file: "icho_kitsune_jo.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "おはぎ", diff: "初級", file: "ohagi_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "お月見", diff: "初級", file: "otsukimi_sho.png", added: "2026-08" },
  { season: "秋", genre: "花", title: "コスモスと蝶", diff: "中級", file: "cosmos_chou_chu.png", added: "2026-08" },
  { season: "秋", genre: "花", title: "コスモス畑", diff: "上級", file: "cosmos_batake_jo.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "こどもの日 その2", diff: "初級", file: "kodomonohi2_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "こどもの日", diff: "中級", file: "kodomonohi_chu.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "さつまいも料理", diff: "中級", file: "satsumaimo_ryori_chu.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "スポーツの日", diff: "初級", file: "sports_no_hi_sho.png", added: "2026-08" },
  { season: "春", genre: "動物", title: "つばめ", diff: "中級", file: "tsubame_chu.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "どんぐり", diff: "中級", file: "donguri_chu.png", added: "2026-08" },
  { season: "春", genre: "動物", title: "ひよことたんぽぽ", diff: "初級", file: "hiyoko_tanpopo_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "みどりの日", diff: "初級", file: "midori_no_hi_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "葵祭", diff: "上級", file: "aoimatsuri_jo.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "衣替え", diff: "中級", file: "koromogae_chu.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "夏の縁側 その2", diff: "上級", file: "natsu_engawa2_jo.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "花より団子", diff: "初級", file: "hanayoridango_sho.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "花より団子 その2", diff: "初級", file: "hanayoridango2_sho.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "海の日", diff: "初級", file: "umi_no_hi_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "幾何学もよう", diff: "初級", file: "kikagaku_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "勤労感謝の日", diff: "初級", file: "kinro_kansha_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "敬老の日", diff: "初級", file: "keirou_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "憲法記念日", diff: "初級", file: "kenpo_kinenbi_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "憲法記念日", diff: "中級", file: "kenpo_kinenbi_chu.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "犬と猫のひなまつり", diff: "初級", file: "inu_neko_hinamatsuri_sho.png", added: "2026-08" },
  { season: "秋", genre: "風景", title: "紅葉と滝", diff: "中級", file: "kouyou_taki_chu.png", added: "2026-08" },
  { season: "春", genre: "花", title: "菜の花と蝶", diff: "初級", file: "nanohana_chou_sho.png", added: "2026-08" },
  { season: "春", genre: "花", title: "桜の幾何学もよう", diff: "初級", file: "sakura_kikagaku_sho.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "山の日", diff: "初級", file: "yama_no_hi_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "時代まつり", diff: "上級", file: "jidaimatsuri_jo.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "七夕猫", diff: "中級", file: "tanabata_neko_chu.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "秋のカーディガン", diff: "中級", file: "aki_cardigan_chu.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "秋の月", diff: "初級", file: "aki_tsuki_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "秋分の日", diff: "初級", file: "shubun_no_hi_sho.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "春キャベツ", diff: "中級", file: "haru_cabbage_chu.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "春の山菜", diff: "中級", file: "haru_sansai_chu.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "春の棚田", diff: "上級", file: "haru_tanada_jo.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "春の風景", diff: "初級", file: "haru_fukei_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "春分の日", diff: "初級", file: "shunbun_no_hi_sho.png", added: "2026-08" },
  { season: "春", genre: "行事", title: "昭和の日", diff: "初級", file: "showa_no_hi_sho.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "織姫と彦星", diff: "中級", file: "orihime_hikoboshi_chu.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "色んなうちわ", diff: "初級", file: "ironna_uchiwa_sho.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "色んなうちわ", diff: "上級", file: "ironna_uchiwa_jo.png", added: "2026-08" },
  { season: "秋", genre: "風景", title: "田んぼのあぜ道と彼岸花", diff: "上級", file: "azemichi_higanbana_jo.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "土用の丑の日", diff: "初級", file: "doyo_ushi_sho.png", added: "2026-08" },
  { season: "通年", genre: "風景", title: "富士山", diff: "初級", file: "fujisan_sho.png", added: "2026-08" },
  { season: "秋", genre: "行事", title: "文化の日", diff: "初級", file: "bunka_no_hi_sho.png", added: "2026-08" },
  { season: "秋", genre: "動物", title: "餅つくうさぎ", diff: "中級", file: "mochitsuki_usagi_chu.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "アイススケート", diff: "中級", file: "ice_skate_chu.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "イルミネーション", diff: "初級", file: "illumination_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "こたつとみかん", diff: "初級", file: "kotatsu_mikan_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "ストーブと湯たんぽ", diff: "中級", file: "stove_yutanpo_chu.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "ぜんざい", diff: "初級", file: "zenzai_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "だるま", diff: "初級", file: "daruma_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "バレンタイン", diff: "中級", file: "valentine_chu.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "マフラーの編み物", diff: "初級", file: "muffler_amimono_sho.png", added: "2026-08" },
  { season: "冬", genre: "食べ物", title: "みかん", diff: "初級", file: "mikan_sho.png", added: "2026-08" },
  { season: "冬", genre: "動物", title: "犬ぞり", diff: "中級", file: "inuzori_chu.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "祝", diff: "初級", file: "iwai_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "小槌", diff: "中級", file: "kozuchi_chu.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "昭和の冬", diff: "中級", file: "showa_fuyu_chu.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "新年", diff: "初級", file: "shinnen_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "正月鯛", diff: "初級", file: "shogatsu_tai_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "雪ウサギ", diff: "初級", file: "yukiusagi_sho.png", added: "2026-08" },
  { season: "冬", genre: "風物詩", title: "雪合戦", diff: "中級", file: "yukigassen_chu.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬", diff: "初級", file: "fuyu_sho.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬の伏見稲荷", diff: "中級", file: "fuyu_fushimiinari_chu.png", added: "2026-08" },
  { season: "冬", genre: "風景", title: "冬の木", diff: "初級", file: "fuyu_ki_sho.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "七夕の笹飾り", diff: "上級", file: "tanabata_kazari_jo.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "天の川と七夕飾り", diff: "上級", file: "amanogawa_tanabata_jo.png", added: "2026-08" },
  { season: "夏", genre: "動物", title: "浮き輪の子猫", diff: "中級", file: "ukiwa_koneko_chu.png", added: "2026-08" },
  { season: "夏", genre: "動物", title: "砂浜のヤドカリ", diff: "上級", file: "yadokari_jo.png", added: "2026-08" },
  { season: "夏", genre: "食べ物", title: "パイナップル", diff: "中級", file: "pineapple_chu.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "鴨川の川床", diff: "上級", file: "kamogawa_yuka_jo.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "屋形船と花火", diff: "中級", file: "yakatabune_hanabi_chu.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "南国の海辺", diff: "初級", file: "nangoku_umibe_sho.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "駄菓子屋", diff: "上級", file: "dagashiya_jo.png", added: "2026-08" },
  { season: "夏", genre: "食べ物", title: "流しそうめん", diff: "中級", file: "nagashi_somen_chu.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "夏祭りの浴衣", diff: "上級", file: "natsumatsuri_yukata_jo.png", added: "2026-08" },
  { season: "夏", genre: "花", title: "朝顔と団扇", diff: "中級", file: "asagao_uchiwa_chu.png", added: "2026-08" },
  { season: "夏", genre: "食べ物", title: "アイスクリーム", diff: "初級", file: "ice_cream_sho.png", added: "2026-08" },
  { season: "夏", genre: "動物", title: "カブトムシとり", diff: "上級", file: "kabutomushi_jo.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "ビニールプール", diff: "中級", file: "vinyl_pool_chu.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "盆踊り", diff: "中級", file: "bonodori_chu.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "おでん その2", diff: "初級", file: "oden2_sho.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "お好み焼き", diff: "初級", file: "okonomiyaki_sho.png", added: "2026-08" },
  { season: "通年", genre: "風景", title: "かやぶきの里", diff: "初級", file: "kayabuki_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "ししおどし", diff: "初級", file: "shishiodoshi_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "ししおどし", diff: "中級", file: "shishiodoshi_chu.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "たこ焼き", diff: "初級", file: "takoyaki_sho.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "ドーナツ", diff: "初級", file: "donut_sho.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "ねずみ", diff: "中級", file: "nezumi_chu.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "バナナ", diff: "初級", file: "banana_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "マグカップ", diff: "初級", file: "mug_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "レトロ喫茶", diff: "初級", file: "retro_kissa_sho.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "夏休み その2", diff: "初級", file: "natsuyasumi2_sho.png", added: "2026-08" },
  { season: "夏", genre: "食べ物", title: "夏野菜 その2", diff: "初級", file: "natsu_yasai2_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "歌舞伎", diff: "中級", file: "kabuki_chu.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "海の中", diff: "上級", file: "umi_naka_jo.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "干し柿 その2", diff: "初級", file: "hoshigaki2_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "喫茶店", diff: "初級", file: "kissaten_sho.png", added: "2026-08" },
  { season: "春", genre: "風景", title: "桜の木 その2", diff: "初級", file: "sakura_ki2_sho.png", added: "2026-08" },
  { season: "春", genre: "食べ物", title: "春の山菜", diff: "初級", file: "haru_sansai_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "生け花", diff: "初級", file: "ikebana_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "大正ロマン", diff: "中級", file: "taisho_roman_chu.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "大正ロマン その2", diff: "中級", file: "taisho_roman2_chu.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "誕生日", diff: "初級", file: "tanjobi_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "茶道", diff: "初級", file: "sado_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "着物", diff: "中級", file: "kimono_chu.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "鳥獣戯画", diff: "上級", file: "chojugiga_jo.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "漬物", diff: "初級", file: "tsukemono_sho.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "鶴と亀", diff: "中級", file: "tsuru_kame_chu.png", added: "2026-08" },
  { season: "夏", genre: "風景", title: "田舎とあじさい", diff: "上級", file: "inaka_ajisai_jo.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "八つ橋", diff: "初級", file: "yatsuhashi_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "盆栽", diff: "初級", file: "bonsai_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "曼荼羅もよう", diff: "初級", file: "mandala_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "お手玉", diff: "初級", file: "otedama_sho.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "かかしととんぼ", diff: "上級", file: "kakashi_tonbo_jo.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "こどもたち", diff: "初級", file: "kodomotachi_sho.png", added: "2026-08" },
  { season: "夏", genre: "行事", title: "ほおずき市", diff: "上級", file: "hozuki_ichi_jo.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "フルーツボウル", diff: "初級", file: "fruits_bowl_sho.png", added: "2026-08" },
  { season: "冬", genre: "行事", title: "七福神", diff: "上級", file: "shichifukujin_jo.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "万華鏡", diff: "初級", file: "mangekyo_sho.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "和風曼荼羅もよう", diff: "初級", file: "wafu_mandala_sho.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "喫茶店のプリン", diff: "中級", file: "kissaten_pudding_chu.png", added: "2026-08" },
  { season: "通年", genre: "食べ物", title: "寿司", diff: "中級", file: "sushi_chu.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "折り紙", diff: "中級", file: "origami_chu.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "昔の遊び", diff: "上級", file: "mukashi_asobi_jo.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "昔の遊び", diff: "中級", file: "mukashi_asobi_chu.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "片羽蝶", diff: "中級", file: "katahane_chou_chu.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "猫と花束", diff: "初級", file: "neko_hanataba_sho.png", added: "2026-08" },
  { season: "秋", genre: "風景", title: "秋の清水寺", diff: "上級", file: "aki_kiyomizudera_jo.png", added: "2026-08" },
  { season: "通年", genre: "風景", title: "竹林の小径", diff: "上級", file: "chikurin_jo.png", added: "2026-08" },
  { season: "春", genre: "花", title: "色んな花", diff: "中級", file: "ironna_hana_chu.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "虎", diff: "上級", file: "tora_jo.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "鶴の折り紙", diff: "初級", file: "tsuru_origami_sho.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "夏の風物詩", diff: "中級", file: "up_1786433365544_1.png", added: "2026-08" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー2", file: "up_1786434439732_1.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "秋のいろいろ", diff: "初級", file: "up_1786434983765_1.png", added: "2026-08" },
  { season: "秋", genre: "風物詩", title: "芸術の秋", diff: "中級", file: "up_1786435376536_2.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "動物の赤ちゃん", diff: "初級", file: "up_1786435623215_3.png", added: "2026-08" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー3", file: "up_1786696005741_1.png", added: "2026-08" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー4", file: "up_1786696469147_2.png", added: "2026-08" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー6", file: "up_1786697020286_1.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "さんま定食", diff: "中級", file: "up_1786697869414_1.png", added: "2026-08" },
  { kind: "カレンダー", year: 2026, month: 9, season: "通年", title: "9月カレンダー7", file: "up_1786698468255_2.png", added: "2026-08" },
  { season: "秋", genre: "食べ物", title: "和菓子", diff: "初級", file: "up_1786698965869_1.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "花火", diff: "上級", file: "up_1786699872178_2.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "送り火", diff: "上級", file: "up_1786709449497_1.png", added: "2026-08" },
  { season: "夏", genre: "風物詩", title: "送り火", diff: "初級", file: "up_1786710655144_2.png", added: "2026-08" },
  { season: "通年", genre: "動物", title: "窓際の猫", diff: "中級", file: "up_1787280884689_1.png", added: "2026-08" },
  { season: "通年", genre: "風景", title: "忍野八海", diff: "上級", file: "up_1787281255003_2.png", added: "2026-08" },
  { season: "通年", genre: "その他", title: "蝶と花の曼荼羅", diff: "初級", file: "up_1787281927634_3.png", added: "2026-08" },
  { season: "通年", title: "動物曼荼羅", diff: "初級", file: "up_1787282123201_4.png", added: "2026-08" },
];
